### PR TITLE
Add Test case for #1 space or \r\n between paragraphs

### PR DESCRIPTION
**Pull request by Ali-YousefiTelori**

### CODE REVIEW

**Comment by SimonCropp** [comment]
but nothing in this PR uses Verify.PdfPig ??

**Comment by Ali-YousefiTelori** [comment]
I didn't change any of the packages, I only added a test case.
both Verify and PDF have this bug.

**Comment by SimonCropp** [comment]
yep. but the test u added only uses pdfpig. i suggest you raise the issue with that project

**Comment by Ali-YousefiTelori** [comment]
@SimonCropp If I add the VerifyPig to the test project we will get a conflict between VerifyPig and pdfpig.
So do you want me to remove pdfpig from test project packages and only use VerifyPig?

**Comment by SimonCropp** [comment]
you have added a test that highlights a bug in `GetPages`. that code exists in PdfPig. i cant do anything in Verify.PdfPig to change that behaviour

**Comment by Ali-YousefiTelori** [comment]
@SimonCropp Ok I'll go to report this bug to PdfPig, thanks.

**Pull request closed without merging**
